CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    password TEXT NOT NULL
);

INSERT INTO users
(email, password)
VALUES
('jasoncarcamo30@yahoo.com', 'Carcamo11!');